//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAttendance.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogInTimeLogDetail
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<System.Guid> UserLogInTimeId { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> LogInTimeID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual UserLoginDetail UserLoginDetail { get; set; }
        public virtual LoginTime LoginTime { get; set; }
    }
}
