//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAttendance.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginTime
    {
        public System.Guid LoginTimeId { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public Nullable<System.TimeSpan> TotalTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ProjectID { get; set; }
        public Nullable<bool> LeaveStatus { get; set; }
    
        public virtual UserLoginDetail UserLoginDetail { get; set; }
        public virtual Project Project { get; set; }
    }
}
