//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAttendance.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingDiagnose
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> EmpId { get; set; }
        public Nullable<System.Guid> DeptId { get; set; }
        public Nullable<System.Guid> PrjId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual Project Project { get; set; }
    }
}
